ccremer/charts

.gitignore, Makefile, bump.go, renovate.json
* Add make target that can bump chart versions
* Configure Renovate so that it executes make target. Don't know if that actually works on GH:
https://docs.renovatebot.com/configuration-options/#postupgradetasks
=> Add make target to automatically bump chart versions

znapzend/Chart.yaml, znapzend/README.md, znapzend/templates/_helpers.tpl, znapzend/templates/configmap.yaml, znapzend/templates/job.yaml, znapzend/templates/rbac.yaml, znapzend/templates/statefulset.yaml, znapzend/test/configmap_test.go, znapzend/test/job_test.go, znapzend/test/main_test.go, znapzend/test/statefulset_test.go, znapzend/test/values/configmap_1.yaml, znapzend/test/values/configmap_2.yaml, znapzend/test/values/configmap_3.yaml, znapzend/test/values/job_1.yaml, znapzend/test/values/job_2.yaml, znapzend/values.yaml
* Adds ConfigMap entry with znapzend-compatible configuration
* Runs a Job to configure znapzendzetup with the backup plans
=> [znapzend] Initialize znapzend with Backup plans

kubernetes-zfs-provisioner/Chart.yaml, kubernetes-zfs-provisioner/README.md, kubernetes-zfs-provisioner/templates/storageclass.yaml, kubernetes-zfs-provisioner/test/storageclass_test.go
* renders an empty value of shareProperties as empty string, not nil. Otherwise Kubernetes fails at validating if the value is empty,
since it would be rendered as nil.
=> [kubernetes-zfs-provisioner] Render string if no parameter is given

.github/workflows/release.yml, kubernetes-zfs-provisioner/Chart.yaml, kubernetes-zfs-provisioner/README.md, kubernetes-zfs-provisioner/templates/storageclass.yaml, kubernetes-zfs-provisioner/test/storageclass_test.go
* Fix a nasty bug, includes test case
* Removes the steps to commit Chart bumps from Workflow, it creates confusion.
=> [kubernetes-zfs-provisioner] Fix wrong Node parameter

.github/readme.sh, charts/kubernetes-zfs-provisioner/Chart.yaml, charts/kubernetes-zfs-provisioner/README.gotmpl.md, charts/kubernetes-zfs-provisioner/README.md, charts/kubernetes-zfs-provisioner/test/storageclass_test.go, charts/kubernetes-zfs-provisioner/test/values/storageclass_1.yaml, charts/kubernetes-zfs-provisioner/values.yaml
* Updates zfs-kubernetes-provisioner to v1, making it stable API
=> [zfs-provisioner] Bump to v1

.github/readme.sh
* Restore old readme structure on gh-pages. (no charts/ subdir)
* Also include values.yaml so that links work
=> Restore old readme structure on gh-pages

README.md, charts/samba/.helmignore, charts/samba/Chart.yaml, charts/samba/README.gotmpl.md, charts/samba/README.md, charts/samba/templates/_helpers.tpl, charts/samba/templates/configmap.yaml, charts/samba/templates/deployment.yaml, charts/samba/templates/pvc.yaml, charts/samba/templates/secret.yaml, charts/samba/templates/serviceaccount.yaml, charts/samba/values.yaml
* Add new Samba helm chart
* Easily allow declarative user and shares definitions
* Add persistent storage
* Based on https://github.com/dperson/samba
=> [samba] Add initial version of samba helm chart

.github/pull_request_template.md, charts/samba/Chart.yaml, charts/samba/README.md, charts/samba/templates/deployment.yaml
* Fixes a template error: executing "samba/templates/deployment.yaml" at <.Values.persistence.volumeMounts>: can't evaluate field Values in type []interface {}
=> [samba] Fix additional volume mount

charts/fronius-exporter/Chart.yaml, charts/fronius-exporter/README.md, charts/fronius-exporter/values.yaml
* Update fronius-exporter to v0.4.0
* Switch to quay.io as default registry
=> [fronius-exporter] Update fronius-exporter to v0.4.0

charts/kubernetes-zfs-provisioner/Chart.yaml, charts/kubernetes-zfs-provisioner/README.md, charts/kubernetes-zfs-provisioner/templates/deployment.yaml, charts/kubernetes-zfs-provisioner/values.yaml
* Add possibility to configure Host Aliases
=> [zfs-provisioner] Add possibility to configure Host Aliases

charts/fronius-exporter/Chart.yaml, charts/fronius-exporter/README.md, charts/fronius-exporter/templates/deployment.yaml, charts/fronius-exporter/test/deployment_test.go, charts/fronius-exporter/test/values/deployment_1.yaml, charts/fronius-exporter/values.yaml
* Add possibility to configure hostAliases
* Rename `fronius:*` to `exporter.*`
=> [fronius-exporter] Add possibility to configure hostAliases

charts/fronius-exporter/Chart.yaml, charts/fronius-exporter/README.md, charts/fronius-exporter/templates/deployment.yaml, charts/fronius-exporter/values.yaml
* Update to v0.5.0
* Add static site label parameter
=> [fronius-exporter] Update to v0.5.0, add static site label

charts/fronius-exporter/Chart.yaml, charts/fronius-exporter/README.md, charts/fronius-exporter/templates/_helpers.tpl, charts/fronius-exporter/templates/deployment.yaml, charts/fronius-exporter/templates/telegraf-secret.yaml, charts/fronius-exporter/values.yaml
* Adds a Telegraf sidecar and config to the exporter deployment. Disabled by default.
=> [fronius-exporter] Add Telegraf sidecar

charts/fronius-exporter/Chart.yaml, charts/fronius-exporter/README.md, charts/fronius-exporter/templates/deployment.yaml, charts/fronius-exporter/templates/telegraf-secret.yaml
* Drop url field from Telegraf metrics, as it's largely useless in a sidecar
* Remove quotes from site name
=> [fronius-exporter] Remove quotes, remove url field

charts/fronius-exporter/Chart.yaml, charts/fronius-exporter/README.md, charts/fronius-exporter/templates/telegraf-secret.yaml, charts/fronius-exporter/test/telegraf_secret_test.go, charts/fronius-exporter/test/values/telegraf_1.yaml, charts/fronius-exporter/values.yaml
* Removes the hostname tag (since Telegraf already adds the `host` field anyway)
* Removes the fielddrop config (wasn't working)
* Adds possibility to define custom global tags
=> [fronius-exporter] Add global tags support

charts/fronius-exporter/Chart.yaml, charts/fronius-exporter/README.md, charts/fronius-exporter/templates/deployment.yaml, charts/fronius-exporter/templates/telegraf-secret.yaml, charts/fronius-exporter/values.yaml
* Remove site parameter and argument
* Ensure global tags are quoted
* Disable telegraf sidecar by default
=> [fronius-exporter] Disable telegraf sidecar by default, remove site parameter

charts/fronius-exporter/Chart.yaml, charts/fronius-exporter/README.gotmpl.md, charts/fronius-exporter/README.md, charts/fronius-exporter/templates/prometheus/service-monitor.yaml, charts/fronius-exporter/test/telegraf_secret_test.go, charts/fronius-exporter/test/values/telegraf_1.yaml, charts/fronius-exporter/values.yaml
=> [fronius-exporter] Add prometheus service monitor

README.md, charts/fronius-stack/.helmignore, charts/fronius-stack/Chart.lock, charts/fronius-stack/Chart.yaml, charts/fronius-stack/README.gotmpl.md, charts/fronius-stack/README.md, charts/fronius-stack/files/grafana/fronius-dashboard.json, charts/fronius-stack/files/influxdb/migration/autonomy.flux, charts/fronius-stack/files/influxdb/migration/energy_day.flux, charts/fronius-stack/files/influxdb/migration/energy_year.flux, charts/fronius-stack/files/influxdb/migration/inverter.flux, charts/fronius-stack/files/influxdb/migration/power_grid.flux, charts/fronius-stack/files/influxdb/migration/power_load.flux, charts/fronius-stack/files/influxdb/migration/power_photo.flux, charts/fronius-stack/files/influxdb/migration/selfconsumption.flux, charts/fronius-stack/files/influxdb/task.sh, charts/fronius-stack/templates/_helpers.tpl, charts/fronius-stack/templates/grafana/cm-dashboard.yaml, charts/fronius-stack/templates/grafana/secret-datasource.yaml, charts/fronius-stack/templates/influxdb/cm-influxdb-task.yaml, charts/fronius-stack/templates/influxdb/job-influxdb-task.yaml, charts/fronius-stack/values.yaml
Installs and configures following charts:
* Fronius exporter with Telegraf sidecar
* InfluxDB v2.x
Extra features:
* Grafana datasource & dashboard (best integrated with Prometheus Operator resp. kube-prometheus-stack)
* Downsampling & archival bucket in InfluxDB
=> [fronius-stack] Add Fronius stack chart

.github/workflows/release.yml, .github/workflows/test.yml, Makefile, charts/clustercode/Chart.yaml, charts/clustercode/Makefile, charts/clustercode/README.md, charts/fronius-stack/Makefile
* Some charts require dependencies which are needed before releasing them.
=> Add prepare target for charts

charts/fronius-stack/Chart.lock, charts/fronius-stack/Chart.yaml, charts/fronius-stack/Makefile, charts/fronius-stack/README.md, charts/fronius-stack/files/grafana/fronius-dashboard.json
* Adjusts the query so that the bars in the time axis of the "Energy per Day" panel starts at the beginning of the day, not where the max value is.
=>  [fronius-stack] Dashboard: fix energy per day time axis

charts/fronius-exporter/Chart.yaml, charts/fronius-exporter/README.md, charts/fronius-exporter/templates/deployment.yaml, charts/fronius-exporter/values.yaml
* Updates image tag to v0.8.0
* Due to braking changes in v0.8.0, the URL in `exporter.symoUrl` should now be only the root URL of the device (e.g. `http://ip.or.hostname`)
* Adds `exporter.endpoints.powerFlow=true`
* Adds `exporter.endpoints.archive=true`
=> [fronius-exporter] Upgrade fronius-exporter to v0.8.0

charts/fronius-stack/Chart.lock, charts/fronius-stack/Chart.yaml, charts/fronius-stack/README.md
* Updates fronius-exporter chart to v0.8.0.
See #88
=> [fronius-stack] Update fronius-exporter chart to v0.8.0

.github/changelog-configuration.json, .github/changelog.sh, .github/workflows/changelog.yml, .gitignore
=> Generate a changelog after helm-chart-releaser published release

charts/fronius-stack/files/grafana/fronius-dashboard.json
* Updates the dashboard for Grafana v8
* This update mainly is required to rename the series "_value" to e.g. "Load"
=> Update Fronius Dashboard to Grafana v8

README.md, charts/emby/Chart.yaml, charts/emby/README.md, charts/emby/templates/deployment.yaml
When updating the chart, it can happen that the new pod
cannot start up since the DB might be locked from the still-running pod
=> Switch deployment strategy to Recreate

README.md, charts/stiebeleltron-exporter/.helmignore, charts/stiebeleltron-exporter/Chart.yaml, charts/stiebeleltron-exporter/README.gotmpl.md, charts/stiebeleltron-exporter/README.md, charts/stiebeleltron-exporter/templates/NOTES.txt, charts/stiebeleltron-exporter/templates/_helpers.tpl, charts/stiebeleltron-exporter/templates/deployment.yaml, charts/stiebeleltron-exporter/templates/ingress.yaml, charts/stiebeleltron-exporter/templates/prometheus/service-monitor.yaml, charts/stiebeleltron-exporter/templates/service.yaml, charts/stiebeleltron-exporter/templates/serviceaccount.yaml, charts/stiebeleltron-exporter/templates/telegraf-secret.yaml, charts/stiebeleltron-exporter/values.yaml
* Add chart for https://github.com/ccremer/stiebeleltron-exporter
=> Add stiebeleltron-exporter chart

README.md, charts/stiebeleltron-stack/Chart.yaml, charts/stiebeleltron-stack/README.md, charts/stiebeleltron-stack/files/grafana/stiebeleltron-dashboard.json
* Removes settings that made the dashboard "sharable externally", which meant that the datasource, bucket and site variables couldn't be populated
=> Fix stiebeleltron dashboard using old datasource variables

README.md, charts/samba/Chart.yaml, charts/samba/README.md, charts/samba/templates/deployment.yaml, charts/samba/templates/pvc.yaml, charts/samba/templates/secret.yaml, charts/samba/values.yaml
* Enable usage of existingSecret for Samba users: It is now possible to define users separate from the chart, e.g. in a SealedSecret.
* Make accessMode for volumes configurable in Samba: For example hostPath PVs do not support ReadWriteMany.
=> existingSecret for users and configurable accessMode for Samba
