.ci/helm-docs.sh, .github/workflows/test.yml, znapzend/Chart.yaml, znapzend/README.md, znapzend/values.yaml
* formats the values.yaml so that the README.md can be generated with [helm-docs ](https://github.com/norwoodj/helm-docs)
=> Trying out helm-docs

.ci/readme.sh, .github/workflows/release.yml, .github/workflows/test.yml
* Updates CI workflows so that the README pages automatically get updated in gh-pages branch
=> Update CI pipeline to auto-update READMEs

.ci/helm-docs.sh, .github/pull_request_template.md, .github/workflows/release.yml, .github/workflows/test.yml, README.md
=> Address pipeline issues

znapzend/Chart.yaml, znapzend/README.md, znapzend/templates/secret.yaml, znapzend/test/secret_test.go, znapzend/test/values/secret_1.yaml, znapzend/test/values/secret_2.yaml, znapzend/test/values/secret_3.yaml
* Bump znapzend version to 0.20.0
Run `docker run --rm -v $(pwd):/src -w /src -u $(id -u) jnorwood/helm-docs` to generate the README.md
=> [znapzend] Bump version, add test

kubernetes-zfs-provisioner/Chart.yaml, kubernetes-zfs-provisioner/README.md, kubernetes-zfs-provisioner/templates/storageclass.yaml, kubernetes-zfs-provisioner/test/go.mod, kubernetes-zfs-provisioner/test/go.sum, kubernetes-zfs-provisioner/test/storageclass_test.go, kubernetes-zfs-provisioner/values.yaml
* Add support for storage class templates
Run `docker run --rm -v $(pwd):/src -w /src -u $(id -u) jnorwood/helm-docs` to generate the README.md
=> [kubernetes-zfs-provisioner] Add StorageClass templates

.ci/readme.sh, .github/pull_request_template.md, .github/workflows/release.yml, .github/workflows/test.yml, Makefile, README.gotmpl, readme.go
Should make things easier for local development but also CI
* Introduces Makefile
* Introduces README generator
Run `docker run --rm -v $(pwd):/src -w /src -u $(id -u) jnorwood/helm-docs` to generate the README.md
=> Introduce Makefile

kubernetes-zfs-provisioner/Chart.yaml, kubernetes-zfs-provisioner/README.md, kubernetes-zfs-provisioner/templates/storageclass.yaml, kubernetes-zfs-provisioner/values.yaml
* Add a note for PodSecurityContext if there are issues reading SSH files.
=> [kubernetes-zfs-provisioner] Add note for PodSecurityContext

kubernetes-zfs-provisioner/Chart.yaml, kubernetes-zfs-provisioner/README.md, kubernetes-zfs-provisioner/values.yaml, znapzend/Chart.yaml, znapzend/README.md, znapzend/values.yaml
* Add and adjust Pod resources. Should make it easier for administrators to perform capacity planning and stabilize clusters.
=> [znapzend][kubernetes-zfs-provisioner] Add and adjust Pod resources

znapzend/Chart.yaml, znapzend/README.md, znapzend/values.yaml
=> [znapzend] Pin image tag

znapzend/Chart.yaml, znapzend/README.md, znapzend/values.yaml
* Bump exporter image to 0.2.2
* Update docker repo to ccremer
=> [znapzend] Bump exporter version

znapzend/Chart.yaml, znapzend/README.md, znapzend/templates/statefulset.yaml, znapzend/values.yaml
* Allows to override container arguments
=> [znapzend] Allow to override image arguments

kubernetes-zfs-provisioner/Chart.yaml, kubernetes-zfs-provisioner/README.md, kubernetes-zfs-provisioner/templates/deployment.yaml, kubernetes-zfs-provisioner/values.yaml, znapzend/Chart.yaml, znapzend/README.md, znapzend/templates/statefulset.yaml, znapzend/values.yaml
* Should make it possible for renovate to create PRs as written in https://docs.renovatebot.com/modules/manager/helm-values/
=> Create dedicated image registry key

znapzend/Chart.yaml, znapzend/README.md, znapzend/templates/configmap.yaml, znapzend/templates/statefulset.yaml, znapzend/test/configmap_test.go, znapzend/values.yaml
* Bump znapzend-exporter image
* Introduce image.registry key also for the exporter image
=> [znapzend] Bump exporter image

.github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, .yamllint.yaml, Makefile, fronius-exporter/Chart.yaml, fronius-exporter/test/values/deployment_1.yaml, kubernetes-zfs-provisioner/Chart.yaml, kubernetes-zfs-provisioner/test/main_test.go, kubernetes-zfs-provisioner/test/secret_test.go, kubernetes-zfs-provisioner/test/storageclass_test.go, kubernetes-zfs-provisioner/test/values/secret_3.yaml, kubernetes-zfs-provisioner/values.yaml, znapzend/templates/rbac.yaml, znapzend/test/main_test.go, znapzend/test/secret_test.go, znapzend/test/values/configmap_1.yaml, znapzend/test/values/configmap_2.yaml, znapzend/test/values/configmap_3.yaml, znapzend/test/values/job_1.yaml, znapzend/test/values/job_2.yaml, znapzend/test/values/secret_3.yaml
* Updates workflows
* reformats source files consistently (identation, etc)
=> GH workflow improvements

znapzend/values.yaml
To test GH action
* Short summary
=> [znapzend] Fake update image

.github/helm-docs-footer.gotmpl.md, .github/helm-docs-header.gotmpl.md, Makefile, README.gotmpl, README.md, clustercode/.helmignore, clustercode/Chart.yaml, clustercode/Makefile, clustercode/README.gotmpl.md, clustercode/README.md, clustercode/kustomize/kustomization.yaml, clustercode/templates/NOTES.txt, clustercode/templates/_helpers.tpl, clustercode/templates/deployment.yaml, clustercode/templates/rbac.yaml, clustercode/templates/service.yaml, clustercode/templates/serviceaccount.yaml, clustercode/values.yaml, emby/README.md, fronius-exporter/README.md, kubernetes-zfs-provisioner/README.md, znapzend/README.md
=> [clustercode] Add Clustercode helm chart

charts/fronius-exporter/Chart.yaml, charts/fronius-exporter/README.md, charts/znapzend/Chart.yaml, charts/znapzend/README.md
* Bumps ApiVersions of some charts
=> [znapzend, fronius] Bump Chart ApiVersion

.github/workflows/lint.yml, .github/workflows/test.yml, Makefile
* Add PR check to detect chart version update
=> Add PR check to detect chart version update

README.gotmpl
* Nothing really.
* To test #92
=> [fronius-stack] Bogus change to test changelog generator

README.gotmpl, README.md, readme.go
* Updates the readme template so that downloads are shows in badges for the latest chart versions
=> Show download badges in readme per chart
